---
# tasks file for httpd
- name: installing httpd
  apt:
    name: httpd
    state: latest
  notify: restart httpd
- name: Copy files
  copy:
    src: index.html
    dest: "{{ dest }}/index.html"
    mode: 0766
    notify: restart httpd
...
